version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: DB          # Replace with your database name
      POSTGRES_USER: admin         # Replace with your database user
      POSTGRES_PASSWORD: a1a1a1  # Replace with your database password
    ports:
      - '5432:5432'                        # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  app:
    build:
      context: ./        # Path to your application's Dockerfile
      dockerfile: Dockerfile              # Name of your Dockerfile
      # container_name: my_app                # Name of your application container
      environment:
        DB_HOST: postgres                   # Hostname of the PostgreSQL container
        DB_PORT: 5432                       # Port for PostgreSQL
        DB_NAME: DB               # Database name
        DB_USER: admin               # Database user
        DB_PASSWORD: a1a1a1       # Database password
      depends_on:
        - postgres                           # Ensure postgres starts before the app
      ports:
        - '3000:3000'                       # Adjust based on your app's port

volumes:
  postgres_data:
