version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a1a1a1
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a1a1a1    
      DATABASE_URL: postgres://admin:a1a1a1@postgres:5432/DB
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
