version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a1a1a1
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://admin:a1a1a1@db/DB
    ports:
      - "8000:8000"
    depends_on:
      - db

